// Reglas clínicas por intolerancia / patología / condición fisiológica.
// Se usan tanto en el prompt del Generador de Planes como en el Recetario.

export function buildIntoleranceRules(
  intolerances: string[],
  pregnancyStage: string = ''
): string {
  return intolerances
    .map(intol => {
      if (intol.includes('Lactosa')) return 'INTOLERANCIA A LA LACTOSA: Prohibido cualquier lácteo con lactosa. Usar leche deslactosada, bebida de almendras, de avena o de soja. Quesos duros (mínimo de lactosa) o queso sin lactosa. Yogur deslactosado.';
      if (intol.includes('Gluten') || intol.includes('Celíaco')) return 'CELÍACO / SIN TACC: Prohibido estrictamente trigo, avena, cebada y centeno (TACC) en cualquier forma. Usar harina de arroz, fécula de mandioca, harina de maíz, copos de arroz, galletitas de arroz, pan sin TACC. Verificar que todos los procesados sean certificados sin TACC.';
      if (intol.includes('Colon Irritable')) return 'COLON IRRITABLE (SII): Seguir pauta baja en FODMAP. Evitar: cebolla, ajo, legumbres, lactosa, trigo en exceso, manzana, pera, mango, miel, fructosa. Preferir: arroz, papa, zanahoria, zapallo, pollo, pescado, huevo, arándanos, frutillas, naranja, mandarina. Cocciones simples, sin frituras ni condimentos irritantes.';
      if (intol.includes('Diverticular')) return 'ENFERMEDAD DIVERTICULAR: Dieta alta en fibra soluble. Evitar semillas pequeñas (chía, sésamo, amapola), frutas con semillas incrustadas (frutillas, higos, kiwi en exceso), porotos enteros. Preferir fibra soluble: avena, zanahoria, calabaza, banana, arroz integral. Buena hidratación.';
      if (intol.includes('SiBO')) return 'SIBO (Sobrecrecimiento Bacteriano Intestinal) — ETAPA INICIAL estricta baja en FODMAP. EVITAR lácteos fermentables (crema de leche, helado, leche, quesos blandos, yogur). Frutos secos y frutas altas en FODMAP: almendras, castañas de cajú, caqui, cereza, ciruela y ciruela desecada, damasco, dátil, durazno, frutas enlatadas, granada, higo, mango, manzana, orejón, pasa de uva, pelón, pera, pistacho, sandía. Vegetales fermentables: ajo, alcaucil, apio, arveja, batata, brócoli, calabaza, cebolla, choclo, coliflor, espárrago, mandioca, puerro, remolacha, repollo. Cereales con gluten y fermentables: trigo, centeno, cebada, amaranto, arroz integral. Legumbres: garbanzo, lenteja, poroto rojo, soja. Dulces y edulcorantes: azúcar, caramelos, chocolate, golosinas, galletitas, edulcorantes terminados en "ol" (sorbitol, manitol, xilitol, maltitol), JMAF, miel, jarabe de arce. Bebidas: bebida de soja, jugos industrializados, ron, vino blanco, gaseosas, cerveza. PERMITIR: arroz blanco, papa, carne, pollo, pescado, huevo, zanahoria, espinaca, lechuga, tomate cherry, arándanos, frutillas, kiwi, naranja, leche sin lactosa, queso duro en poca cantidad. Estrategia: probar tolerancia progresivamente y luego transicionar hacia una DIETA MEDITERRÁNEA.';
      if (intol.includes('Hipertensión')) return 'HIPERTENSIÓN ARTERIAL: Restricción estricta de sodio. EVITAR: embutidos, fiambres, quesos maduros, snacks salados (papas fritas, palitos), comida rápida, sopas instantáneas, caldos en cubo, conservas con sal, aderezos comerciales, salsa de soja, encurtidos. INCLUIR: pescado 2 veces/semana (sardina, salmón, caballa, atún), aceite de oliva extra virgen, palta, frutos secos sin sal, vegetales y frutas frescas, legumbres, cereales integrales. Priorizar hierbas y especias (orégano, pimentón, comino, laurel, ajo fresco) en lugar de sal. Patrón DASH.';
      if (intol.includes('Diabetes')) return 'DIABETES: EVITAR azúcares simples, miel, jarabe de maíz de alta fructosa y alcohol. Evitar preparaciones que generen picos glucémicos como licuados, puré o jugos exprimidos de frutas. INCLUIR fibra en cada comida (verduras, legumbres, semillas de chía y lino), cereales integrales (arroz integral, avena, quinoa, pan integral) y EVITAR harinas refinadas. No pasar más de 4 horas sin comer y distribuir los hidratos en todas las comidas. Elegir frutas enteras con piel en lugar de jugos.';
      if (intol.includes('Colesterol')) return 'COLESTEROL ALTO (Hipercolesterolemia): Restringir grasa saturada (<7% VCT) y colesterol dietario (<200 mg/día). Priorizar omega-3: aumentar consumo de pescado fresco 2-3 veces/semana (salmón, caballa, atún, anchoa, arenque, sardina, mariscos). Carnes rojas magras máximo 2 veces/semana y pollo sin piel. Aumentar fibra alimentaria total — fibra soluble: avena, legumbres (arvejas, porotos, garbanzos, soja, lentejas), manzana, pera, cebada, cítricos, zanahoria, brócoli; también arroz o fideos integrales, pastas semoladas de trigo candeal, salvado de trigo, quinoa, amaranto. Esteroles vegetales. Aceites y semillas: oliva extra virgen, canola, soja, lino, chía, sésamo, frutos secos (almendras, nueces, castañas de cajú). EVITAR: fiambres, embutidos, vísceras (hígado, riñón), piel de pollo, lácteos enteros, manteca, crema, bollería, margarina, fritos y ultraprocesados.';
      if (intol.includes('Triglicéridos')) return 'TRIGLICÉRIDOS ALTOS (Hipertrigliceridemia): Reducir azúcares simples y fructosa libre al mínimo. Alcohol CERO. Limitar harinas refinadas y productos de panadería. Aumentar omega-3 (pescado azul 2-3 veces/semana: caballa, sardina, jurel, salmón, atún) y fibra soluble. Fomentar ejercicio aeróbico. EVITAR: jugos de fruta (incluso naturales), gaseosas, bebidas azucaradas, miel, dulces, mermeladas, pastelería, helados, cereales azucarados. SUGERIR como suplemento: cápsulas de chía u omega-3 de alta concentración.';
      if (intol.includes('Fructosa')) return 'INTOLERANCIA A LA FRUCTOSA: Evitar fructosa libre y polioles. PROHIBIDAS: coco, granada, mango, manzana, melón, papaya, pera, sandía, ciruela, membrillo, durazno, damasco. Jugos de manzana y pera, frutas deshidratadas, jugos industriales. EVITAR ingredientes: fructosa, jarabe de fructosa, jarabe de maíz de alta fructosa, sorbitol, maltitol, xilitol, isomalt, agave, miel. Bebidas prohibidas: whisky, vermouth. Condimentos: ketchup y salsas comerciales que contengan jarabe de maíz o fructosa. PERMITIDAS CON MODERACIÓN: bananas bien maduras, frutillas, arándanos, kiwi, limón, naranja.';
      if (intol.includes('Deportista')) return 'DEPORTISTA: Proteína a 1.7 g/kg (ya aplicado en el requerimiento). Priorizar timing nutricional: proteína post-entreno (20-30 g de proteína de alta calidad dentro de los 30-60 min siguientes). Hidratos de absorción lenta pre-entreno (avena, arroz integral, batata); hidratos de absorción rápida post-entreno (banana, dátiles, arroz blanco). Incluir 2-3 colaciones proteicas-energéticas entre comidas. Hidratación 35-40 ml/kg + 500 ml adicionales por hora de entrenamiento. Electrolitos en sesiones >60 min. NOTA: el nivel de actividad física sólo afecta el cálculo calórico; esta pauta aplica a cualquier paciente con objetivo de ganancia o mantenimiento de masa muscular (ej: IMC normal que busca hipertrofia).';
      if (intol.includes('Embarazo y Lactancia')) {
        const stageLabel = pregnancyStage ? ` (ETAPA: ${pregnancyStage})` : '';
        return `EMBARAZO Y LACTANCIA${stageLabel}: Proteína a 1.5 g/kg. Calcio 1200 mg/día (lácteos 3-4 porciones/día, almendras, brócoli, kale, espinaca, sardinas con espina, tofu con calcio). Hierro 27 mg/día (carne roja magra 2-3 veces/semana, lentejas con vitamina C, espinaca, morcilla cocida — combinar con cítricos para absorción). Ácido fólico 600 mcg (verduras de hoja verde oscuro, legumbres, cítricos, palta). Omega-3 DHA (pescado azul bajo en mercurio: sardina, caballa, salmón 2 veces/semana — EVITAR ESTRICTAMENTE atún rojo, pez espada, tiburón, caballa rey por alto contenido de mercurio). Yodo (sal yodada, lácteos). PROHIBIDOS: embutidos crudos, quesos blandos no pasteurizados (brie, camembert, feta, roquefort sin pasteurizar), pescado y carne crudos (sushi, ceviche, carpaccio), alcohol, cafeína >200 mg/día (máximo 2 tazas café), paté, vísceras, huevos crudos. ESQUEMA: 3 comidas principales + 2-3 colaciones (evitar ayunos prolongados, náuseas). Incluir porción de lácteo en desayuno, merienda y una colación.`;
      }
      if (intol.includes('Menopausia')) return 'MENOPAUSIA: Proteína a 1.0 g/kg para preservar masa magra. Calcio 1200 mg/día (lácteos descremados 3 porciones, sardinas con espina, almendras, semillas de sésamo, tofu con calcio, brócoli). EVITAR inhibidores de absorción de calcio: café, té, mate, bebidas energizantes, exceso de sodio en snacks salados, fiambres, embutidos y ultraprocesados; bebidas colas (fósforo). Promover REMOJO de legumbres y cereales para eliminar fitatos y mejorar absorción de calcio/hierro. Vitamina D (exposición solar 15 min/día + pescado azul + yema de huevo, considerar suplementación). Magnesio (frutos secos, palta, cacao amargo 70%+, semillas de zapallo). Fitoestrógenos (soja, tofu, tempeh, lino molido, legumbres). Carbohidratos de absorción lenta (legumbres, cereales integrales). Reducir azúcares simples y grasas saturadas. Limitar cafeína y alcohol (impactan densidad ósea y sofocos). Priorizar alimentos que apoyen salud cardiovascular post-menopáusica. RECOMENDACIÓN: sumar ejercicio de fuerza 2-3 veces/semana para densidad ósea.';
      if (intol.includes('GLP-1')) return 'MEDICACIÓN ANÁLOGA DE GLP-1 (Saxenda / liraglutide / semaglutide): Priorizar saciedad con calidad nutricional. PROTEÍNAS MAGRAS en cada comida (pollo, pescado, huevo, yogur, legumbres). FIBRA clave: verduras (eje de cada comida), frutas enteras, avena, semillas. GRASAS SALUDABLES en pequeñas cantidades (palta, frutos secos, aceite de oliva). CARBOHIDRATOS DE ABSORCIÓN LENTA (avena, arroz integral, legumbres). Comer lento y fraccionado — 4 a 5 comidas chicas/día para evitar síntomas gastrointestinales (náuseas, reflujo). EVITAR: comidas grasas o fritas, alcohol, bebidas gaseosas, cargas altas en una sola comida.';
      return '';
    })
    .filter(Boolean)
    .join('\n');
}
