-- ═══════════════════════════════════════════════════════════════════════════
-- ARCHIVO MOVIDO
-- ═══════════════════════════════════════════════════════════════════════════
-- Las migraciones SQL ahora viven organizadas por feature en:
--
--   supabase/migrations/
--
-- Cada migración está numerada (001..010) y es idempotente. Ver
-- supabase/migrations/README.md para el detalle de qué hace cada una y
-- el orden de ejecución.
--
-- Si querés pegar TODO de una sola vez en el SQL Editor de Supabase, usá:
--
--   supabase/migrations/apply_all.sql
--
-- (es la concatenación auto-generada de todas las migraciones en orden).
-- ═══════════════════════════════════════════════════════════════════════════
